Exp-4-postsection

diff --git a/week-03-docker/Jenkinsfile b/week-03-docker/Jenkinsfile
--- a/week-03-docker/Jenkinsfile
+++ b/week-03-docker/Jenkinsfile
@@ -17,13 +17,9 @@ pipeline {
 
         stage('Unit Tests') {
     steps {
-        script {
-            try {
-                sh 'exit 1'
-            }
-            catch(Exception e) {
-                echo "Test Failed But Continuing"
-            }
+        dir('week-03-docker') {
+           sh 'exit 1'
+            sh 'npm test'
         }
     }
 }
@@ -74,9 +70,16 @@ pipeline {
     }
 
     post {
-        always {
-            sh 'docker logout || true'
-            echo 'Pipeline completed'
-        }
+
+    success {
+        echo 'SUCCESS BLOCK'
+    }
+
+    failure {
+        echo 'FAILURE BLOCK'
+    }
+
+    always {
+        echo 'ALWAYS BLOCK'
     }
 }
